# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5fca93e99e1297ef871ae0a1d8ff2938a807591795367f7729755090e8dd0b26fb3cd03858cd6b05722f2931be75d1903c38a933fa8ad8304a29cf962676d86a

test:
  secret_key_base: f7b09692a47664dab41951d8f0b009c9c89f855528dfd50299b279824c35c2e863a5cbeff7b9bdf676134b58ed2fe792f08ba8d0b5e9e09be7350b0095dd2ca6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
